// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/builder.tsx";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/upload.tsx";
import * as $$0 from "./islands/Button.tsx";
import * as $$1 from "./islands/Header.tsx";
import * as $$2 from "./islands/UploadForm.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/builder.tsx": $2,
    "./routes/index.tsx": $3,
    "./routes/upload.tsx": $4,
  },
  islands: {
    "./islands/Button.tsx": $$0,
    "./islands/Header.tsx": $$1,
    "./islands/UploadForm.tsx": $$2,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
